### PR TITLE
Create initial GVK

### LINKED ISSUE #1: Create API Types
Create GVK

Potential options:

* `terraforms.argoproj.io`
* `terraforms.infra.argoproj.io`

### PR DESCRIPTION
**Pull request by christianh814**
Create initial Group and Kind of `terraforms.infra.argoproj.io` with version of `v1alpha1`

Fixes #1 

Signed-off-by: Christian Hernandez <chernand@redhat.com>

### CODE REVIEW

**Review by sabre1041 — DISMISSED** [review]
~LGTM~

**Comment by sabre1041** [comment]
@christianh814 is there a reason `infras` is included in the group name?

**Comment by christianh814** [comment]
> @christianh814 is there a reason `infras` is included in the group name?

Two reasons

* I don't know how not to include the group in the `operatorsdk` command 😬
* I didn't want to mention long term plans because I want to get this out fast and introduce scope creep. But I want to plan for future controllers Argo CD can call (e.g. `ansible-runner`)

I don't mind not using it and I don't want to introduce more questions about "future" design

**Comment by sabre1041** [comment]
@christianh814 

1. You can omit the inclusion of the group in the `operator-sdk`. Just dont pass the parameter
2. Using `ApplicationSet` as an example. It alway omitted the use of a subdomani

**Comment by christianh814** [comment]
@sabre1041 Okay updated by [c5ce91c](https://github.com/sabre1041/argocd-terraform-controller/pull/11/commits/c5ce91c75879d54f020078b9b0abf65bf1e9e9ba) has no group

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
